/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using YoutubeSearchAPI.Standard.Controllers;
using YoutubeSearchAPI.Standard.Http.Client;
using YoutubeSearchAPI.Standard.Utilities;

namespace YoutubeSearchAPI.Standard
{
    public partial class YoutubeSearchAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public YoutubeSearchAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public YoutubeSearchAPIClient(string key = "AIzaSyDUvW2Jbb0ob8a2tDidm8RQzYxczT2OroA")
        {
            Configuration.Key = key;
        }
        #endregion
    }
}