/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;


namespace YoutubeSearchAPI.Standard.Models
{
    public class Item : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string kind;
        private string etag;
        private Models.Id id;
        private Models.Snippet snippet;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kind")]
        public string Kind 
        { 
            get 
            {
                return this.kind; 
            } 
            set 
            {
                this.kind = value;
                onPropertyChanged("Kind");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("etag")]
        public string Etag 
        { 
            get 
            {
                return this.etag; 
            } 
            set 
            {
                this.etag = value;
                onPropertyChanged("Etag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public Models.Id Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("snippet")]
        public Models.Snippet Snippet 
        { 
            get 
            {
                return this.snippet; 
            } 
            set 
            {
                this.snippet = value;
                onPropertyChanged("Snippet");
            }
        }
    }
} 