/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;


namespace YoutubeSearchAPI.Standard.Models
{
    public class PageInfo : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int totalResults;
        private int resultsPerPage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("totalResults")]
        public int TotalResults 
        { 
            get 
            {
                return this.totalResults; 
            } 
            set 
            {
                this.totalResults = value;
                onPropertyChanged("TotalResults");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("resultsPerPage")]
        public int ResultsPerPage 
        { 
            get 
            {
                return this.resultsPerPage; 
            } 
            set 
            {
                this.resultsPerPage = value;
                onPropertyChanged("ResultsPerPage");
            }
        }
    }
} 