/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;


namespace YoutubeSearchAPI.Standard.Models
{
    public class Snippet : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string publishedAt;
        private string channelId;
        private string title;
        private string description;
        private Models.Thumbnails thumbnails;
        private string channelTitle;
        private string liveBroadcastContent;
        private string publishTime;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("publishedAt")]
        public string PublishedAt 
        { 
            get 
            {
                return this.publishedAt; 
            } 
            set 
            {
                this.publishedAt = value;
                onPropertyChanged("PublishedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("channelId")]
        public string ChannelId 
        { 
            get 
            {
                return this.channelId; 
            } 
            set 
            {
                this.channelId = value;
                onPropertyChanged("ChannelId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("thumbnails")]
        public Models.Thumbnails Thumbnails 
        { 
            get 
            {
                return this.thumbnails; 
            } 
            set 
            {
                this.thumbnails = value;
                onPropertyChanged("Thumbnails");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("channelTitle")]
        public string ChannelTitle 
        { 
            get 
            {
                return this.channelTitle; 
            } 
            set 
            {
                this.channelTitle = value;
                onPropertyChanged("ChannelTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("liveBroadcastContent")]
        public string LiveBroadcastContent 
        { 
            get 
            {
                return this.liveBroadcastContent; 
            } 
            set 
            {
                this.liveBroadcastContent = value;
                onPropertyChanged("LiveBroadcastContent");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("publishTime")]
        public string PublishTime 
        { 
            get 
            {
                return this.publishTime; 
            } 
            set 
            {
                this.publishTime = value;
                onPropertyChanged("PublishTime");
            }
        }
    }
} 