/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;


namespace YoutubeSearchAPI.Standard.Models
{
    public class Thumbnails : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Default mdefault;
        private Models.Medium medium;
        private Models.High high;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("default")]
        public Models.Default Default 
        { 
            get 
            {
                return this.mdefault; 
            } 
            set 
            {
                this.mdefault = value;
                onPropertyChanged("Default");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("medium")]
        public Models.Medium Medium 
        { 
            get 
            {
                return this.medium; 
            } 
            set 
            {
                this.medium = value;
                onPropertyChanged("Medium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("high")]
        public Models.High High 
        { 
            get 
            {
                return this.high; 
            } 
            set 
            {
                this.high = value;
                onPropertyChanged("High");
            }
        }
    }
} 