/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;


namespace YoutubeSearchAPI.Standard.Models
{
    public class YoutubeJSONMasterObject : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string kind;
        private string etag;
        private string nextPageToken;
        private string regionCode;
        private Models.PageInfo pageInfo;
        private List<Models.Item> items;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kind")]
        public string Kind 
        { 
            get 
            {
                return this.kind; 
            } 
            set 
            {
                this.kind = value;
                onPropertyChanged("Kind");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("etag")]
        public string Etag 
        { 
            get 
            {
                return this.etag; 
            } 
            set 
            {
                this.etag = value;
                onPropertyChanged("Etag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nextPageToken")]
        public string NextPageToken 
        { 
            get 
            {
                return this.nextPageToken; 
            } 
            set 
            {
                this.nextPageToken = value;
                onPropertyChanged("NextPageToken");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("regionCode")]
        public string RegionCode 
        { 
            get 
            {
                return this.regionCode; 
            } 
            set 
            {
                this.regionCode = value;
                onPropertyChanged("RegionCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pageInfo")]
        public Models.PageInfo PageInfo 
        { 
            get 
            {
                return this.pageInfo; 
            } 
            set 
            {
                this.pageInfo = value;
                onPropertyChanged("PageInfo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("items")]
        public List<Models.Item> Items 
        { 
            get 
            {
                return this.items; 
            } 
            set 
            {
                this.items = value;
                onPropertyChanged("Items");
            }
        }
    }
} 