# -*- coding: utf-8 -*-

"""
    apimaticcalculatornew

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class OperationEnum(object):

    """Implementation of the 'operation' enum.

    TODO: type enum description here.

    Attributes:
        SUM: TODO: type description here.
        SUBTRACT: TODO: type description here.
        MULTIPLY: TODO: type description here.
        DIVIDE: TODO: type description here.

    """

    SUM = 'SUM'

    SUBTRACT = 'SUBTRACT'

    MULTIPLY = 'MULTIPLY'

    DIVIDE = 'DIVIDE'

