/*
 * YoutubeSearchAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using YoutubeSearchAPI.Standard;
using YoutubeSearchAPI.Standard.Utilities;
using YoutubeSearchAPI.Standard.Http.Request;
using YoutubeSearchAPI.Standard.Http.Response;
using YoutubeSearchAPI.Standard.Http.Client;
using YoutubeSearchAPI.Standard.Exceptions;

namespace YoutubeSearchAPI.Standard.Controllers
{
    public partial class APIController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static APIController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static APIController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new APIController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="part">Required parameter: The part parameter specifies a comma-separated list of one or more search resource properties that the API response will include. Set the parameter value to snippet.</param>
        /// <param name="q">Required parameter: The q parameter specifies the query term to search for.</param>
        /// <param name="type">Optional parameter: The type parameter restricts a search query to only retrieve a particular type of resource.</param>
        /// <return>Returns the Models.YoutubeJSONMasterObject response from the API call</return>
        public Models.YoutubeJSONMasterObject SearchEndpoint(Models.PartEnum part, string q, string type = null)
        {
            Task<Models.YoutubeJSONMasterObject> t = SearchEndpointAsync(part, q, type);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="part">Required parameter: The part parameter specifies a comma-separated list of one or more search resource properties that the API response will include. Set the parameter value to snippet.</param>
        /// <param name="q">Required parameter: The q parameter specifies the query term to search for.</param>
        /// <param name="type">Optional parameter: The type parameter restricts a search query to only retrieve a particular type of resource.</param>
        /// <return>Returns the Models.YoutubeJSONMasterObject response from the API call</return>
        public async Task<Models.YoutubeJSONMasterObject> SearchEndpointAsync(Models.PartEnum part, string q, string type = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/search");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "part", Models.PartEnumHelper.ToValue(part) },
                { "q", q },
                { "type", type },
                { "key", Configuration.Key }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new RootException(@"Custom 400 Error message occurred", _context);

            if (_response.StatusCode == 401)
                throw new RootException(@"Custom 401 Error Message Occurred", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.YoutubeJSONMasterObject>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 